[2023-11-26T07:38:44.031+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetch_clean_elastic.clean_data manual__2023-11-26T07:38:37.714775+00:00 [queued]>
[2023-11-26T07:38:44.037+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetch_clean_elastic.clean_data manual__2023-11-26T07:38:37.714775+00:00 [queued]>
[2023-11-26T07:38:44.037+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-11-26T07:38:44.037+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2023-11-26T07:38:44.038+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-11-26T07:38:44.046+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): clean_data> on 2023-11-26 07:38:37.714775+00:00
[2023-11-26T07:38:44.052+0000] {standard_task_runner.py:52} INFO - Started process 224 to run task
[2023-11-26T07:38:44.055+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_clean_elastic', 'clean_data', 'manual__2023-11-26T07:38:37.714775+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_Sifra_Siregar_DAG.py', '--cfg-path', '/tmp/tmp4c72bqis', '--error-file', '/tmp/tmpz00cxqbu']
[2023-11-26T07:38:44.057+0000] {standard_task_runner.py:80} INFO - Job 3: Subtask clean_data
[2023-11-26T07:38:44.110+0000] {task_command.py:371} INFO - Running <TaskInstance: fetch_clean_elastic.clean_data manual__2023-11-26T07:38:37.714775+00:00 [running]> on host 159ad28653d9
[2023-11-26T07:38:44.157+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sifra
AIRFLOW_CTX_DAG_ID=fetch_clean_elastic
AIRFLOW_CTX_TASK_ID=clean_data
AIRFLOW_CTX_EXECUTION_DATE=2023-11-26T07:38:37.714775+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-26T07:38:37.714775+00:00
[2023-11-26T07:38:44.272+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_Sifra_Siregar_DAG.py", line 103, in clean
    data = data.astype(data_types)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5799, in astype
    col.astype(dtype=dtype[col_name], copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1174, in astype_nansafe
    return lib.astype_intsafe(arr, dtype)
  File "pandas/_libs/lib.pyx", line 679, in pandas._libs.lib.astype_intsafe
ValueError: cannot convert float NaN to integer
[2023-11-26T07:38:44.280+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_clean_elastic, task_id=clean_data, execution_date=20231126T073837, start_date=20231126T073844, end_date=20231126T073844
[2023-11-26T07:38:44.286+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task clean_data (cannot convert float NaN to integer; 224)
[2023-11-26T07:38:44.311+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-26T07:38:44.329+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
